# Generated by Django 5.0.7 on 2024-07-19 02:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paises_detalle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('poblacion', models.IntegerField()),
                ('area', models.FloatField()),
            ],
        ),
    ]
